spring: #띄어쓰기 없음
  datasource: #띄어쓰기 2칸
    url: jdbc:h2:tcp://localhost/~/jpashop7 #4칸
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

#  naver:
#    url:
#      search:
#        local: https://openapi.naver.com/v1/search/local.json
#        image: https://openapi.naver.com/v1/search/image
#    client:
#      id: Zi3o1uQftp59zuIqEAz4
#      secret: iy6YKSWpLM

  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: none #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        #      show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸

logging: #띄어쓰기 없음
  level:
    org.hibernate.SQL: debug #띄어쓰기 2칸
    org.hibernate.type: trace #띄어쓰기 2칸



